version: "2"

linters:
  default: none
  enable:
    - loglinter
  settings:
    custom:
      loglinter:
        type: "module"
        description: "Checks log messages style"
        settings:
          check_uppercase: true
          check_language: true
          check_special_symbols: true
          check_sensitive: true
          sensitive:
            - "password"
            - "pwd"
            - "pass"
            - "token"
            - "api_key"
            - "apikey"
            - "key"
            - "secret"
            - "credential"
            - "jwt"
            - "auth"
            - "private_key"
            - "certificate"
            - "cert"
            - "ssn"
            - "credit_card"
            - "bank_account"
          punctuation:
            - ","
            - "."
            - "!"
            - "?"
            - "\""
            - "'"
            - ":"
            - ";"